"""empty message

Revision ID: e5dfa4d61852
Revises: 758fbba26403
Create Date: 2017-03-20 14:30:11.737382

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e5dfa4d61852'
down_revision = '758fbba26403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('littlecloud_filegroup',
    sa.Column('littlecloud_id', sa.Integer(), nullable=True),
    sa.Column('filegroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filegroup_id'], ['filegroups.id'], ),
    sa.ForeignKeyConstraint(['littlecloud_id'], ['littleclouds.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('littlecloud_filegroup')
    # ### end Alembic commands ###
